### ISSUE TITLE
com.bytedance.sdk.openadsdk.multipro.TTmultiprovider禁用后占CPU高

### ISSUE THREAD

**Issue by 345000346** [lihenggui/blocker-general-rules#1]
com.bytedance.sdk.openadsdk.multipro.TTmultiprovider禁用后占CPU高，建议排除

**Comment by lihenggui** [comment]
https://github.com/lihenggui/blocker-general-rules/commit/aafe512c1a06b58828877d5144b5b74065d17b03

可能得考虑一下如何做一个黑名单

**Comment by 345000346** [comment]
只排除这一个就行了，其他的com.bytedance.sdk.openadsdk.还是要禁用的，是得做个黑名单了。
