### ISSUE TITLE
增加规则sigmob

### ISSUE THREAD

**Issue by him007** [lihenggui/blocker-general-rules#18]
com.sigmob.sdk.base.common.TransparentAdActivity
com.sigmob.sdk.base.common.TransparentAdActivity
[官网](https://www.sigmob.com/)
[官方文档安卓接入](https://doc.sigmob.com/Sigmob%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/SDK%E9%9B%86%E6%88%90%E8%AF%B4%E6%98%8E/Android/SDK%E6%8E%A5%E5%85%A5%E9%85%8D%E7%BD%AE/)

**Comment by lihenggui** [comment]
看起来可以直接检测com.sigmob.sdk.
