### ISSUE TITLE
Oppo广告联盟规则需要增加com.opos.mobad.

### ISSUE THREAD

**Issue by him007** [lihenggui/blocker-general-rules#20]
- com.opos.mobad.service.AdService
- com.opos.mobad.service.DownloadService
- com.opos.mobad.activity.AdActivity
- com.opos.cmn.biz.web.activity.apiimpl.AdWebActivity
- com.opos.cmn.an.transactivity.api.TransActivity
- com.opos.mobad.activity.VideoActivity
- com.opos.mobad.provider.MobAdGlobalProvider

com.opos.cmn.这两个禁用了好像也没问题

OPPO 广告 SDK 对接文档: [https://open.oppomobile.com/new/developmentDoc/info?id=11495](https://open.oppomobile.com/new/developmentDoc/info?id=11495)

**Comment by lihenggui** [comment]
可以直接禁用com.opos.cmn.下的所有组件吗

**Comment by lihenggui** [comment]
com.opos.mobad. 已经在规则里了
https://github.com/lihenggui/blocker-general-rules/blob/main/rules/zh-cn/general.json#L587
