### ISSUE TITLE
新增魅族广告组件

### ISSUE THREAD

**Issue by nmsglmg** [lihenggui/blocker-general-rules#28]
com.meizu.customizecenter.AdWebActivity

com.meizu.customizecenter.frame.activity.AdWebActivity

com.meizu.customizecenter.frame.activity.StartAppAdActivity

com.meizu.customizecenter.frame.activity.CustomizeCenterActivity

**Comment by nmsglmg** [comment]
刚刚又双叕发现的魅族广告组件，tm的

com.common.advertise.xxx

com.meizu.advertise.xxx

**Comment by lihenggui** [comment]
com.common.advertise.这个包名对吗
